update documents d
set category = v.category,
    secondary_tags = coalesce(nullif(d.secondary_tags, ''), v.topic),
    ref_period = coalesce(nullif(d.ref_period, ''), v.year),
    original_author = coalesce(nullif(d.original_author, ''), v.autore),
    author = case when v.autore = 'Chiara Lubich' then 'CHIA' else d.author end
from (values
(507, 'Ge3', 'Gen 3', null, null),
(522, 'Ge3', 'Chiara risposte gen 3', null, null),
(577, 'Tlk', 'Temi di Chiara', null, 'Chiara Lubich'),
(578, 'Tlk', 'Temi di Chiara', null, 'Chiara Lubich'),
(601, 'Exp', 'Primi Pope e Popi', null, 'Vale Ronchetti'),
(602, 'Tlk', 'scuola abba', null, 'Marisa Cerini'),
(603, 'Col', 'Congresso Mariano ', null, null),
(607, 'Ge4', 'slides', null, null),
(608, 'Ge4', 'Gen 4', null, null),
(609, 'Exp', 'Primi Pope e Popi', null, 'Dori'),
(610, 'Ge4', 'slides', null, null),
(611, 'Ge4', 'slides', null, null),
(612, 'Ge4', 'slides', null, null),
(614, 'Ge4', 'slides', null, null),
(615, 'Ge4', 'Gen 4', null, null),
(616, 'Ge4', 'slides', null, null),
(618, 'Ge4', 'slides', null, null),
(628, 'Vol', 'Volontari', null, null),
(629, 'Vol', 'Volontari', null, null),
(630, 'Vol', 'Volontari', null, null),
(631, 'Col', '10 Comandamenti', null, null),
(637, 'Dlg', 'Musulmani', null, null),
(650, 'NFa', 'Famiglie Nuove', null, null),
(651, 'NFa', 'Famiglie Nuove', null, null),
(652, 'NFa', 'Famiglie Nuove', null, null),
(654, 'Col', '10 Comandamenti', null, null),
(655, 'NFa', 'Famiglie Nuove', null, null),
(658, 'Dlg', 'Musulmani', null, null),
(666, 'Ge4', 'Gen 4', null, null),
(755, 'Lkp', 'Collegamento', '1998', null),
(953, 'Wol', 'Parola di Vita', null, null),
(965, 'Var', 'Digiuno', null, null),
(967, 'Ge2', 'Gen 2', null, null),
(983, 'Exp', 'Primi Pope e Popi', null, 'Dori'),
(989, 'Ge3', 'Gen 3', null, null),
(993, 'Dlg', 'Musulmani', null, null),
(994, 'Dlg', 'Musulmani', null, null),
(1050, 'Ge4', 'Gen 4', null, null),
(1052, 'Ge4', 'Gen 4', null, null),
(1060, 'Exp', 'Primi Pope e Popi', null, 'Ginetta'),
(1123, 'Ge3', 'Gen 3', null, null),
(1128, 'Col', 'La Fiammella', null, null),
(1131, 'Lett', 'Lettere', null, null),
(1132, 'Lett', 'Lettere', null, null),
(1133, 'Lett', 'Lettere', null, null),
(1134, 'Lett', 'Lettere', null, null),
(1147, 'Dlg', 'Musulmani', null, null),
(1151, 'Lett', 'Lettere', null, null),
(1153, 'Lett', 'Lettere', null, null),
(1155, 'Lett', 'Lettere', null, null),
(1156, 'NFa', 'Famiglie Nuove', null, null),
(1159, 'Lett', 'Lettere', null, null),
(1161, 'Lett', 'Lettere', null, null),
(1167, 'Lett', 'Lettere', null, null),
(1177, 'Mdt', 'Meditazioni', null, null),
(1178, 'Mdt', 'Meditazioni', null, null),
(1179, 'Mdt', 'Meditazioni', null, null),
(1180, 'Mdt', 'Meditazioni', null, null),
(1181, 'Mdt', 'Meditazioni', null, null),
(1182, 'Mdt', 'Meditazioni', null, null),
(1183, 'Mdt', 'Meditazioni', null, null),
(1184, 'Mdt', 'Meditazioni', null, null),
(1185, 'Mdt', 'Meditazioni', null, null),
(1186, 'Mdt', 'Meditazioni', null, null),
(1187, 'Mdt', 'Meditazioni', null, null),
(1188, 'Mdt', 'Meditazioni', null, null),
(1189, 'Mdt', 'Meditazioni', null, null),
(1190, 'Mdt', 'Meditazioni', null, null),
(1191, 'Mdt', 'Meditazioni', null, null),
(1192, 'Mdt', 'Meditazioni', null, null),
(1193, 'Mdt', 'Meditazioni', null, null),
(1194, 'Mdt', 'Meditazioni', null, null),
(1195, 'Mdt', 'Meditazioni', null, null),
(1196, 'Mdt', 'Meditazioni', null, null),
(1197, 'Mdt', 'Meditazioni', null, null),
(1198, 'Mdt', 'Meditazioni', null, null),
(1199, 'Mdt', 'Meditazioni', null, null),
(1200, 'Mdt', 'Meditazioni', null, null),
(1201, 'Mdt', 'Meditazioni', null, null),
(1202, 'Mdt', 'Meditazioni', null, null),
(1203, 'Mdt', 'Meditazioni', null, null),
(1204, 'Mdt', 'Meditazioni', null, null),
(1205, 'Mdt', 'Meditazioni', null, null),
(1206, 'Mdt', 'Meditazioni', null, null),
(1207, 'Mdt', 'Meditazioni', null, null),
(1208, 'Mdt', 'Meditazioni', null, null),
(1209, 'Mdt', 'Meditazioni', null, null),
(1210, 'Mdt', 'Meditazioni', null, null),
(1211, 'Mdt', 'Meditazioni', null, null),
(1212, 'Mdt', 'Meditazioni', null, null),
(1213, 'Mdt', 'Meditazioni', null, null),
(1214, 'Mdt', 'Meditazioni', null, null),
(1215, 'Ctc', 'Settimana Santa', null, null),
(1216, 'Mdt', 'Meditazioni', null, null),
(1217, 'Mdt', 'Meditazioni', null, null),
(1218, 'Mdt', 'Meditazioni', null, null),
(1219, 'Mdt', 'Meditazioni', null, null),
(1220, 'Mdt', 'Meditazioni', null, null),
(1221, 'Mdt', 'Meditazioni', null, null),
(1222, 'Mdt', 'Meditazioni', null, null)
) as v(document_id, category, topic, year, autore)
where v.document_id = d.document_id;

select 'updated' as label, count(*) as n from (values
(507, 'Ge3', 'Gen 3', null, null),
(522, 'Ge3', 'Chiara risposte gen 3', null, null),
(577, 'Tlk', 'Temi di Chiara', null, 'Chiara Lubich'),
(578, 'Tlk', 'Temi di Chiara', null, 'Chiara Lubich'),
(601, 'Exp', 'Primi Pope e Popi', null, 'Vale Ronchetti'),
(602, 'Tlk', 'scuola abba', null, 'Marisa Cerini'),
(603, 'Col', 'Congresso Mariano ', null, null),
(607, 'Ge4', 'slides', null, null),
(608, 'Ge4', 'Gen 4', null, null),
(609, 'Exp', 'Primi Pope e Popi', null, 'Dori'),
(610, 'Ge4', 'slides', null, null),
(611, 'Ge4', 'slides', null, null),
(612, 'Ge4', 'slides', null, null),
(614, 'Ge4', 'slides', null, null),
(615, 'Ge4', 'Gen 4', null, null),
(616, 'Ge4', 'slides', null, null),
(618, 'Ge4', 'slides', null, null),
(628, 'Vol', 'Volontari', null, null),
(629, 'Vol', 'Volontari', null, null),
(630, 'Vol', 'Volontari', null, null),
(631, 'Col', '10 Comandamenti', null, null),
(637, 'Dlg', 'Musulmani', null, null),
(650, 'NFa', 'Famiglie Nuove', null, null),
(651, 'NFa', 'Famiglie Nuove', null, null),
(652, 'NFa', 'Famiglie Nuove', null, null),
(654, 'Col', '10 Comandamenti', null, null),
(655, 'NFa', 'Famiglie Nuove', null, null),
(658, 'Dlg', 'Musulmani', null, null),
(666, 'Ge4', 'Gen 4', null, null),
(755, 'Lkp', 'Collegamento', '1998', null),
(953, 'Wol', 'Parola di Vita', null, null),
(965, 'Var', 'Digiuno', null, null),
(967, 'Ge2', 'Gen 2', null, null),
(983, 'Exp', 'Primi Pope e Popi', null, 'Dori'),
(989, 'Ge3', 'Gen 3', null, null),
(993, 'Dlg', 'Musulmani', null, null),
(994, 'Dlg', 'Musulmani', null, null),
(1050, 'Ge4', 'Gen 4', null, null),
(1052, 'Ge4', 'Gen 4', null, null),
(1060, 'Exp', 'Primi Pope e Popi', null, 'Ginetta'),
(1123, 'Ge3', 'Gen 3', null, null),
(1128, 'Col', 'La Fiammella', null, null),
(1131, 'Lett', 'Lettere', null, null),
(1132, 'Lett', 'Lettere', null, null),
(1133, 'Lett', 'Lettere', null, null),
(1134, 'Lett', 'Lettere', null, null),
(1147, 'Dlg', 'Musulmani', null, null),
(1151, 'Lett', 'Lettere', null, null),
(1153, 'Lett', 'Lettere', null, null),
(1155, 'Lett', 'Lettere', null, null),
(1156, 'NFa', 'Famiglie Nuove', null, null),
(1159, 'Lett', 'Lettere', null, null),
(1161, 'Lett', 'Lettere', null, null),
(1167, 'Lett', 'Lettere', null, null),
(1177, 'Mdt', 'Meditazioni', null, null),
(1178, 'Mdt', 'Meditazioni', null, null),
(1179, 'Mdt', 'Meditazioni', null, null),
(1180, 'Mdt', 'Meditazioni', null, null),
(1181, 'Mdt', 'Meditazioni', null, null),
(1182, 'Mdt', 'Meditazioni', null, null),
(1183, 'Mdt', 'Meditazioni', null, null),
(1184, 'Mdt', 'Meditazioni', null, null),
(1185, 'Mdt', 'Meditazioni', null, null),
(1186, 'Mdt', 'Meditazioni', null, null),
(1187, 'Mdt', 'Meditazioni', null, null),
(1188, 'Mdt', 'Meditazioni', null, null),
(1189, 'Mdt', 'Meditazioni', null, null),
(1190, 'Mdt', 'Meditazioni', null, null),
(1191, 'Mdt', 'Meditazioni', null, null),
(1192, 'Mdt', 'Meditazioni', null, null),
(1193, 'Mdt', 'Meditazioni', null, null),
(1194, 'Mdt', 'Meditazioni', null, null),
(1195, 'Mdt', 'Meditazioni', null, null),
(1196, 'Mdt', 'Meditazioni', null, null),
(1197, 'Mdt', 'Meditazioni', null, null),
(1198, 'Mdt', 'Meditazioni', null, null),
(1199, 'Mdt', 'Meditazioni', null, null),
(1200, 'Mdt', 'Meditazioni', null, null),
(1201, 'Mdt', 'Meditazioni', null, null),
(1202, 'Mdt', 'Meditazioni', null, null),
(1203, 'Mdt', 'Meditazioni', null, null),
(1204, 'Mdt', 'Meditazioni', null, null),
(1205, 'Mdt', 'Meditazioni', null, null),
(1206, 'Mdt', 'Meditazioni', null, null),
(1207, 'Mdt', 'Meditazioni', null, null),
(1208, 'Mdt', 'Meditazioni', null, null),
(1209, 'Mdt', 'Meditazioni', null, null),
(1210, 'Mdt', 'Meditazioni', null, null),
(1211, 'Mdt', 'Meditazioni', null, null),
(1212, 'Mdt', 'Meditazioni', null, null),
(1213, 'Mdt', 'Meditazioni', null, null),
(1214, 'Mdt', 'Meditazioni', null, null),
(1215, 'Ctc', 'Settimana Santa', null, null),
(1216, 'Mdt', 'Meditazioni', null, null),
(1217, 'Mdt', 'Meditazioni', null, null),
(1218, 'Mdt', 'Meditazioni', null, null),
(1219, 'Mdt', 'Meditazioni', null, null),
(1220, 'Mdt', 'Meditazioni', null, null),
(1221, 'Mdt', 'Meditazioni', null, null),
(1222, 'Mdt', 'Meditazioni', null, null)
) as v(document_id, category, topic, year, autore);
