update documents d
set category = v.category,
    secondary_tags = coalesce(nullif(d.secondary_tags, ''), v.topic),
    ref_period = coalesce(nullif(d.ref_period, ''), v.year),
    original_author = coalesce(nullif(d.original_author, ''), v.autore),
    author = case when v.autore = 'Chiara Lubich' then 'CHIA' else d.author end
from (values
(1223, 'Mdt', 'Meditazioni', null, null),
(1224, 'Mdt', 'Meditazioni', null, null),
(1225, 'Mdt', 'Meditazioni', null, null),
(1226, 'Ctc', 'Settimana Santa', null, null),
(1227, 'Mdt', 'Meditazioni', null, null),
(1228, 'Ctc', 'Settimana Santa', null, null),
(1229, 'Mdt', 'Meditazioni', null, null),
(1232, 'Ge3', 'Gen 3', null, null),
(1235, 'Mdt', 'Meditazioni', null, null),
(1238, 'Chi', 'Partenza di Chiara', null, null),
(1239, 'Mdt', 'Meditazioni', null, null),
(1240, 'Mdt', 'Meditazioni', null, null),
(1247, 'Dlg', 'Musulmani', null, null),
(1248, 'Wol', 'Parola di Vita', '2000', null),
(1249, 'Wol', 'Parola di Vita', '2000', null),
(1252, 'Var', 'Vari Opera', null, null),
(1262, 'Col', 'libro La casa sulla roccia', null, null),
(1404, 'Dlg', 'Musulmani', null, null),
(1405, 'Dlg', 'Musulmani', null, null),
(1407, 'Dlg', 'Musulmani', null, null),
(1465, 'Ge3', 'Scuola Mariana gen 3', null, null),
(1468, 'Ge3', 'Scuola Mariana gen 3', null, null),
(1486, 'Reg', 'Statuti Opera di Maria', null, null),
(1487, 'Reg', 'Statuti Opera di Maria', null, null),
(1513, 'NFa', 'Famiglie Nuove', null, null),
(1544, 'Ge2', 'Gen 2', null, null),
(1555, 'NFa', 'Famiglie Nuove', null, null)
) as v(document_id, category, topic, year, autore)
where v.document_id = d.document_id;

select 'updated' as label, count(*) as n from (values
(1223, 'Mdt', 'Meditazioni', null, null),
(1224, 'Mdt', 'Meditazioni', null, null),
(1225, 'Mdt', 'Meditazioni', null, null),
(1226, 'Ctc', 'Settimana Santa', null, null),
(1227, 'Mdt', 'Meditazioni', null, null),
(1228, 'Ctc', 'Settimana Santa', null, null),
(1229, 'Mdt', 'Meditazioni', null, null),
(1232, 'Ge3', 'Gen 3', null, null),
(1235, 'Mdt', 'Meditazioni', null, null),
(1238, 'Chi', 'Partenza di Chiara', null, null),
(1239, 'Mdt', 'Meditazioni', null, null),
(1240, 'Mdt', 'Meditazioni', null, null),
(1247, 'Dlg', 'Musulmani', null, null),
(1248, 'Wol', 'Parola di Vita', '2000', null),
(1249, 'Wol', 'Parola di Vita', '2000', null),
(1252, 'Var', 'Vari Opera', null, null),
(1262, 'Col', 'libro La casa sulla roccia', null, null),
(1404, 'Dlg', 'Musulmani', null, null),
(1405, 'Dlg', 'Musulmani', null, null),
(1407, 'Dlg', 'Musulmani', null, null),
(1465, 'Ge3', 'Scuola Mariana gen 3', null, null),
(1468, 'Ge3', 'Scuola Mariana gen 3', null, null),
(1486, 'Reg', 'Statuti Opera di Maria', null, null),
(1487, 'Reg', 'Statuti Opera di Maria', null, null),
(1513, 'NFa', 'Famiglie Nuove', null, null),
(1544, 'Ge2', 'Gen 2', null, null),
(1555, 'NFa', 'Famiglie Nuove', null, null)
) as v(document_id, category, topic, year, autore);
